<link href="assets/css/jquery-confirm.css" rel="stylesheet" type="text/css">
<link href="assets/css/fonts.css" rel="stylesheet" type="text/css">
<link href="assets/css/icons/icomoon/styles.min.css" rel="stylesheet" type="text/css">
<link href="assets/css/bootstrap.min.css" rel="stylesheet" type="text/css">
<link href="assets/css/bootstrap_limitless.min.css" rel="stylesheet" type="text/css">
<link href="assets/css/layout.min.css" rel="stylesheet" type="text/css">
<link href="assets/css/components.min.css" rel="stylesheet" type="text/css">
<link href="assets/css/colors.min.css" rel="stylesheet" type="text/css">
<link href="assets/css/helper.css" rel="stylesheet" type="text/css">
<link href="assets/css/common.css" rel="stylesheet" type="text/css">
<link href="assets/css/sweetalert.css" rel="stylesheet" type="text/css">
<link href="assets/css/updatesinprogess.css" rel="stylesheet" type="text/css">
